[package]
name = "bevy_ambient_cg"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0", features = ["basis-universal", "jpeg", "pbr_transmission_textures"] }
image = "0.25.5"
